// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_KeVGkeovCBJKUbuMlMaJT73ODnBS9rg',
    appId: '1:899976306993:web:3031bf0cbb2bf424a35010',
    messagingSenderId: '899976306993',
    projectId: 'tailoringstorage',
    authDomain: 'tailoringstorage.firebaseapp.com',
    storageBucket: 'tailoringstorage.firebasestorage.app',
    measurementId: 'G-YTCD2HVXHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOdNVfdUcVT50BELtBpfGaTClY1G7_o0',
    appId: '1:899976306993:android:7be2f879a959bd87a35010',
    messagingSenderId: '899976306993',
    projectId: 'tailoringstorage',
    storageBucket: 'tailoringstorage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3dg7U7RXSf9-NPRry6WKfKKyzzltWcg',
    appId: '1:899976306993:ios:fcbde4b7d68dae10a35010',
    messagingSenderId: '899976306993',
    projectId: 'tailoringstorage',
    storageBucket: 'tailoringstorage.firebasestorage.app',
    iosBundleId: 'com.example.tailoringapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT3dg7U7RXSf9-NPRry6WKfKKyzzltWcg',
    appId: '1:899976306993:ios:fcbde4b7d68dae10a35010',
    messagingSenderId: '899976306993',
    projectId: 'tailoringstorage',
    storageBucket: 'tailoringstorage.firebasestorage.app',
    iosBundleId: 'com.example.tailoringapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_KeVGkeovCBJKUbuMlMaJT73ODnBS9rg',
    appId: '1:899976306993:web:c9bd76256bb6d32ba35010',
    messagingSenderId: '899976306993',
    projectId: 'tailoringstorage',
    authDomain: 'tailoringstorage.firebaseapp.com',
    storageBucket: 'tailoringstorage.firebasestorage.app',
    measurementId: 'G-QF20W8VLCS',
  );
}
